### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by NianBroken** [chen310/NeteaseCloudMusicTasks#110] opened 2022-03-15 11:48 UTC
START RequestId: 9ae2500c-1b20-4aad-8b94-1fc77a0af767

Init Report RequestId: 9ae2500c-1b20-4aad-8b94-1fc77a0af767 Coldstart: 1846ms (PullCode: 324ms InitRuntime: 59ms InitFunction: 1463ms) Memory: 128MB MemUsage: 22.62MB

### 用户1

Starting new HTTPS connection (1): music.163.com:443

https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52

https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 437

#### 用户信息

- 登录失败，{'code': -462, 'data': {'actionCode': '1076401', 'verifyType': 40, 'verifyId': 1007602, 'verifyUrl': 'https://st.music.163.com/encrypt-pages', 'blockText': '验证成功后，可进行下一步操作哦~', 'verifyToken': '00.40.96f041f491ac5cda57d58655b81e98b6.2709341008', 'btnText': '', 'orpheusUrl': '', 'frontRuleIds': [1076401], 'params': {'event_id': '00211810552988897305', 'sign': '42da396cf3c185991c85cea214877908'}, 'url': 'https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%2242da396cf3c185991c85cea214877908%22%2C%22event_id%22%3A%2200211810552988897305%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.96f041f491ac5cda57d58655b81e98b6.2709341008&actionCode=1076401'}, 'message': None}

Starting new HTTPS connection (1): qyapi.weixin.qq.com:443

https://qyapi.weixin.qq.com:443 "GET /cgi-bin/gettoken?corpid=ww651565dc7e94dd15&corpsecret=gTUeC6Bwo0wPsTwH6KpEgpn5D8Ev_C4GdpTKhS97y80 HTTP/1.1" 200 277

Starting new HTTPS connection (1): qyapi.weixin.qq.com:443

https://qyapi.weixin.qq.com:443 "POST /cgi-bin/message/send?access_token=7douT2uyVnrjVNgCSaitSy103Xoq9nAwox8zG2jRVz19ruuSZvJydSG9hb-fskmXjRzCGsIdNDqTAkVQ348l6ytt9i30uGTxiiX1b2z1A8XK64GdNBgGbj4YwPKsq0ZnujQi8SOPOjvp7RgXm3oAborrkNSEuyO0JqmGkrM_W5e3Z1PILjde8wJ3C-JdKbn9aUjtmjeDsK_NrUZyuVNXNg HTTP/1.1" 200 124

Response RequestId:9ae2500c-1b20-4aad-8b94-1fc77a0af767 RetMsg:null

END RequestId:9ae2500c-1b20-4aad-8b94-1fc77a0af767

Report RequestId:9ae2500c-1b20-4aad-8b94-1fc77a0af767 Duration:430ms Memory:128MB MemUsage:39.621094MB

**Comment by chen310** [comment] 2022-03-15 11:51
Duplicate of #105

**Closed by chen310** 2022-03-15 11:51 UTC
