### ISSUE TITLE
测试失败

### ISSUE THREAD

**Issue by NianBroken** [chen310/NeteaseCloudMusicTasks#123] opened 2022-03-17 07:08 UTC
START RequestId: 81c1b0f0-09f4-40a5-b363-9068a4300272

Init Report RequestId: 81c1b0f0-09f4-40a5-b363-9068a4300272 Coldstart: 474ms (PullCode: 7ms InitRuntime: 4ms InitFunction: 463ms) Memory: 128MB MemUsage: 16.38MB

ERROR RequestId: 81c1b0f0-09f4-40a5-b363-9068a4300272 Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 6, in <module>     import json5 ModuleNotFoundError: No module named 'json5'", "statusCode": 443}

END RequestId: 81c1b0f0-09f4-40a5-b363-9068a4300272

Report RequestId: 81c1b0f0-09f4-40a5-b363-9068a4300272 Duration: 0ms Memory: 128MB MemUsage: 16.38MB

START RequestId:81c1b0f0-09f4-40a5-b363-9068a4300272

ERROR RequestId:81c1b0f0-09f4-40a5-b363-9068a4300272 Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 6, in \u003cmodule\u003e\n    import json5\nModuleNotFoundError: No module named 'json5'","statusCode":443}

END RequestId:81c1b0f0-09f4-40a5-b363-9068a4300272

Report RequestId:81c1b0f0-09f4-40a5-b363-9068a4300272 Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by chen310** [comment] 2022-03-17 07:11
Duplicate of #28

**Comment by chen310** [comment] 2022-03-17 07:12
没有绑定层

**Closed by chen310** 2022-03-17 07:12 UTC

**Comment by NianBroken** [comment] 2022-03-17 07:18
![image](https://user-images.githubusercontent.com/57057288/158756730-f7591c3b-78aa-4e40-8c38-eac54f152461.png)
![image](https://user-images.githubusercontent.com/57057288/158756762-fa3b6da6-874b-444f-a8d9-ec8492e99b7a.png)
添加依赖后依然错误
