### ISSUE TITLE
执行报错。。

### ISSUE THREAD

**Issue by maya1900** [chen310/NeteaseCloudMusicTasks#113] opened 2022-03-16 01:18 UTC
START RequestId: ed03caf2-2292-47a6-bf5e-851286628a3f

Init Report RequestId: ed03caf2-2292-47a6-bf5e-851286628a3f Coldstart: 555ms (PullCode: 97ms InitRuntime: 5ms InitFunction: 453ms) Memory: 128MB MemUsage: 16.35MB

ERROR RequestId: ed03caf2-2292-47a6-bf5e-851286628a3f Result: {"errorCode": -1, "errorMessage": "Traceback (most recent call last):   File "/var/runtime/python3/bootstrap.py", line 133, in init_handler     func_handler = get_func_handler(file.rsplit(".", 1)[0], func)   File "/var/runtime/python3/bootstrap.py", line 159, in get_func_handler     mod = imp.load_module(mname, *imp.find_module(mname))   File "/var/lang/python3/lib/python3.6/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/python3/lib/python3.6/imp.py", line 172, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 675, in _load   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 678, in exec_module   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed   File "/var/user/index.py", line 6, in <module>     import json5 ModuleNotFoundError: No module named 'json5'", "statusCode": 443}

END RequestId: ed03caf2-2292-47a6-bf5e-851286628a3f

Report RequestId: ed03caf2-2292-47a6-bf5e-851286628a3f Duration: 0ms Memory: 128MB MemUsage: 16.35MB

START RequestId:ed03caf2-2292-47a6-bf5e-851286628a3f

ERROR RequestId:ed03caf2-2292-47a6-bf5e-851286628a3f Result:{"errorCode":-1,"errorMessage":"Traceback (most recent call last):\n  File \"/var/runtime/python3/bootstrap.py\", line 133, in init_handler\n    func_handler = get_func_handler(file.rsplit(\".\", 1)[0], func)\n  File \"/var/runtime/python3/bootstrap.py\", line 159, in get_func_handler\n    mod = imp.load_module(mname, *imp.find_module(mname))\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/var/lang/python3/lib/python3.6/imp.py\", line 172, in load_source\n    module = _load(spec)\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 675, in _load\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 655, in _load_unlocked\n  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 678, in exec_module\n  File \"\u003cfrozen importlib._bootstrap\u003e\", line 205, in _call_with_frames_removed\n  File \"/var/user/index.py\", line 6, in \u003cmodule\u003e\n    import json5\nModuleNotFoundError: No module named 'json5'","statusCode":443}

END RequestId:ed03caf2-2292-47a6-bf5e-851286628a3f

Report RequestId:ed03caf2-2292-47a6-bf5e-851286628a3f Duration:0ms Memory:128MB MemUsage:0.000000MB

**Comment by maya1900** [comment] 2022-03-16 01:31
云函数，请教大佬

**Comment by chen310** [comment] 2022-03-16 01:32
Duplicate of #28

**Comment by maya1900** [comment] 2022-03-16 01:32
收到了你的邮件哦，会尽快回复的。。   --Mr. Ma

**Closed by chen310** 2022-03-16 01:32 UTC
