### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by Ele-sorriu** [chen310/NeteaseCloudMusicTasks#109] opened 2022-03-15 09:58 UTC
登录失败，{'code': -462, 'data': {'actionCode': '1076401', 'verifyType': 40, 'verifyId': 1007602, 'verifyUrl': 'https://st.music.163.com/encrypt-pages', 'blockText': '验证成功后，可进行下一步操作哦~', 'verifyToken': '00.40.5ab7f6fb23fce6046b31f5f8535803b2.4027420492', 'btnText': '', 'orpheusUrl': '', 'frontRuleIds': [1076401](https://sct.ftqq.com/readpush?id=49679620&readkey=SCT3DCx2jmq5mKl), 'params': {'event_id': '00211781240822607901', 'sign': '26e7194362f4b267e4b0c55ad1ad3ab5'}, 'url': '[https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%2226e7194362f4b267e4b0c55ad1ad3ab5%22%2C%22event_id%22%3A%2200211781240822607901%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.5ab7f6fb23fce6046b31f5f8535803b2.4027420492&actionCode=1076401'}](https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%2226e7194362f4b267e4b0c55ad1ad3ab5%22%2C%22event_id%22%3A%2200211781240822607901%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.5ab7f6fb23fce6046b31f5f8535803b2.4027420492&actionCode=1076401%27}), 'message': None}

这是怎么了  账号密码没问题  登录保护也关了

**Comment by chen310** [comment] 2022-03-15 10:21
Duplicate of #105

**Closed by chen310** 2022-03-15 10:21 UTC
