### ISSUE TITLE
腾讯云函数，突然出现的user code exception caught

### ISSUE THREAD

**Issue by powerfullz** [chen310/NeteaseCloudMusicTasks#88] opened 2022-03-09 12:41 UTC
部署完成之后几天一切正常，这几天出现user code exception caught的错误，账号一切正常，日志如下。

---
Starting new HTTPS connection (1): music.163.com:443
https://music.163.com:443 "POST /weapi/user/level HTTP/1.1" 200 52
https://music.163.com:443 "POST /weapi/login/cellphone HTTP/1.1" 200 983
已通过账号密码登录
https://music.163.com:443 "POST /weapi/v1/user/detail/535224542 HTTP/1.1" 200 1033
**用户信息**
用户名称: `TimCock`
用户ID: `535224542`
用户等级: `8`
用户村龄: `1707天`
https://music.163.com:443 "POST /weapi/music-vip-membership/client/vip/info HTTP/1.1" 200 67
ERROR RequestId:a4c5a23a-c26a-4925-b79b-7937fab568f7 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 154, in main_handler\n    start(event, context)\n  File \"/var/user/index.py\", line 77, in start\n    user.startTask()\n  File \"/var/user/user.py\", line 817, in startTask\n    self.userInfo()\n  File \"/var/user/user.py\", line 167, in userInfo\n    self.taskInfo('VIP等级', vip_resp['data']['redVipLevel'])\nKeyError: 'data'","statusCode":430}
END RequestId:a4c5a23a-c26a-4925-b79b-7937fab568f7
Report RequestId:a4c5a23a-c26a-4925-b79b-7937fab568f7 Duration:480ms Memory:128MB MemUsage:22.363708MB

**Comment by chen310** [comment] 2022-03-09 13:33
删掉云函数，更新一下代码，重新部署试试

**Comment by chen310** [comment] 2022-03-12 07:35
Duplicate of #80

**Closed** 2022-03-12 07:35 UTC
